/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import java.sql.Connection;
import util.ConnectionFactory;

public class Main {

    public static void main(String[] args) throws ClassNotFoundException {

        Connection c = ConnectionFactory.getConnection();

        ConnectionFactory.closeConnection(c);

    }
}
